package com.gtd.android.ui.theme

import androidx.compose.ui.graphics.Color

data class ContextThemeColorScheme(
    val background: Color,
    val headerBg: Color,
    val headerBorder: Color,
    val headerText: Color,
    val headerSubtext: Color,
    val sidebarBg: Color,
    val sidebarLabel: Color,
    val sidebarItemText: Color,
    val sidebarItemActive: Color,
    val sidebarItemActiveText: Color,
    val mainBg: Color,
    val taskText: Color,
    val taskCompletedText: Color,
    val taskSubtext: Color,
    val taskCardBg: Color,
    val taskDivider: Color,
    val checkboxBorder: Color,
    val checkboxChecked: Color,
    val progressBg: Color,
    val progressFill: Color,
    val btnPrimary: Color,
    val btnPrimaryText: Color,
    val inputBg: Color,
    val inputBorder: Color,
    val inputText: Color,
    val accentColor: Color,
    val badgeBg: Color,
    val badgeText: Color,
    val cardBg: Color,
    val isDark: Boolean,
)

val MinimalistTheme = ContextThemeColorScheme(
    background = Color(0xFFFAFAF9),
    headerBg = Color(0xFFFFFFFF),
    headerBorder = Color(0xFFE7E5E4),
    headerText = Color(0xFF1C1917),
    headerSubtext = Color(0xFFA8A29E),
    sidebarBg = Color(0xFFFFFFFF),
    sidebarLabel = Color(0xFFA8A29E),
    sidebarItemText = Color(0xFF57534E),
    sidebarItemActive = Color(0xFFF5F5F4),
    sidebarItemActiveText = Color(0xFF1C1917),
    mainBg = Color(0xFFFFFFFF),
    taskText = Color(0xFF292524),
    taskCompletedText = Color(0xFFA8A29E),
    taskSubtext = Color(0xFFA8A29E),
    taskCardBg = Color(0xFFFFFFFF),
    taskDivider = Color(0xFFF5F5F4),
    checkboxBorder = Color(0xFFD6D3D1),
    checkboxChecked = Color(0xFFE7E5E4),
    progressBg = Color(0xFFE7E5E4),
    progressFill = Color(0xFF78716C),
    btnPrimary = Color(0xFF1C1917),
    btnPrimaryText = Color(0xFFFFFFFF),
    inputBg = Color(0xFFFFFFFF),
    inputBorder = Color(0xFFE7E5E4),
    inputText = Color(0xFF292524),
    accentColor = Color(0xFF78716C),
    badgeBg = Color(0xFFF5F5F4),
    badgeText = Color(0xFF78716C),
    cardBg = Color(0xFFF5F5F5),
    isDark = false,
)

val DesignTheme = ContextThemeColorScheme(
    background = Color(0xFFF5F3FF),
    headerBg = Color(0xFFFFFFFF),
    headerBorder = Color(0xFFEDE9FE),
    headerText = Color(0xFF4C1D95),
    headerSubtext = Color(0xFFA78BFA),
    sidebarBg = Color(0xFFF5F3FF),
    sidebarLabel = Color(0xFFA78BFA),
    sidebarItemText = Color(0xFF7C3AED),
    sidebarItemActive = Color(0xFFEDE9FE),
    sidebarItemActiveText = Color(0xFF4C1D95),
    mainBg = Color(0xFFFFFFFF),
    taskText = Color(0xFF5B21B6),
    taskCompletedText = Color(0xFFC4B5FD),
    taskSubtext = Color(0xFFA78BFA),
    taskCardBg = Color(0xFFFFFFFF),
    taskDivider = Color(0xFFEDE9FE),
    checkboxBorder = Color(0xFFC4B5FD),
    checkboxChecked = Color(0xFFDDD6FE),
    progressBg = Color(0xFFDDD6FE),
    progressFill = Color(0xFF7C3AED),
    btnPrimary = Color(0xFF7C3AED),
    btnPrimaryText = Color(0xFFFFFFFF),
    inputBg = Color(0xFFFFFFFF),
    inputBorder = Color(0xFFDDD6FE),
    inputText = Color(0xFF5B21B6),
    accentColor = Color(0xFF7C3AED),
    badgeBg = Color(0xFFEDE9FE),
    badgeText = Color(0xFF7C3AED),
    cardBg = Color(0xFFF5F3FF),
    isDark = false,
)

val FormalTheme = ContextThemeColorScheme(
    background = Color(0xFFF8FAFC),
    headerBg = Color(0xFFFFFFFF),
    headerBorder = Color(0xFFE2E8F0),
    headerText = Color(0xFF0F172A),
    headerSubtext = Color(0xFF94A3B8),
    sidebarBg = Color(0xFFF8FAFC),
    sidebarLabel = Color(0xFF94A3B8),
    sidebarItemText = Color(0xFF475569),
    sidebarItemActive = Color(0xFFF1F5F9),
    sidebarItemActiveText = Color(0xFF0F172A),
    mainBg = Color(0xFFFFFFFF),
    taskText = Color(0xFF1E293B),
    taskCompletedText = Color(0xFF94A3B8),
    taskSubtext = Color(0xFF94A3B8),
    taskCardBg = Color(0xFFFFFFFF),
    taskDivider = Color(0xFFF1F5F9),
    checkboxBorder = Color(0xFFCBD5E1),
    checkboxChecked = Color(0xFFE2E8F0),
    progressBg = Color(0xFFE2E8F0),
    progressFill = Color(0xFF64748B),
    btnPrimary = Color(0xFF1E293B),
    btnPrimaryText = Color(0xFFFFFFFF),
    inputBg = Color(0xFFFFFFFF),
    inputBorder = Color(0xFFE2E8F0),
    inputText = Color(0xFF1E293B),
    accentColor = Color(0xFF475569),
    badgeBg = Color(0xFFF1F5F9),
    badgeText = Color(0xFF64748B),
    cardBg = Color(0xFFF9FAFB),
    isDark = false,
)

val NatureTheme = ContextThemeColorScheme(
    background = Color(0xFFF0FDF4),
    headerBg = Color(0xFFFFFFFF),
    headerBorder = Color(0xFFD1FAE5),
    headerText = Color(0xFF064E3B),
    headerSubtext = Color(0xFF34D399),
    sidebarBg = Color(0xFFF0FDF4),
    sidebarLabel = Color(0xFF10B981),
    sidebarItemText = Color(0xFF047857),
    sidebarItemActive = Color(0xFFD1FAE5),
    sidebarItemActiveText = Color(0xFF064E3B),
    mainBg = Color(0xFFFFFFFF),
    taskText = Color(0xFF065F46),
    taskCompletedText = Color(0xFF6EE7B7),
    taskSubtext = Color(0xFF34D399),
    taskCardBg = Color(0xFFFFFFFF),
    taskDivider = Color(0xFFD1FAE5),
    checkboxBorder = Color(0xFF6EE7B7),
    checkboxChecked = Color(0xFFA7F3D0),
    progressBg = Color(0xFFA7F3D0),
    progressFill = Color(0xFF10B981),
    btnPrimary = Color(0xFF059669),
    btnPrimaryText = Color(0xFFFFFFFF),
    inputBg = Color(0xFFFFFFFF),
    inputBorder = Color(0xFFA7F3D0),
    inputText = Color(0xFF065F46),
    accentColor = Color(0xFF059669),
    badgeBg = Color(0xFFD1FAE5),
    badgeText = Color(0xFF059669),
    cardBg = Color(0xFFF0FDF4),
    isDark = false,
)

val DarkTheme = ContextThemeColorScheme(
    background = Color(0xFF18181B),
    headerBg = Color(0xFF27272A),
    headerBorder = Color(0xFF3F3F46),
    headerText = Color(0xFFF4F4F5),
    headerSubtext = Color(0xFF71717A),
    sidebarBg = Color(0xFF27272A),
    sidebarLabel = Color(0xFF71717A),
    sidebarItemText = Color(0xFFA1A1AA),
    sidebarItemActive = Color(0xFF3F3F46),
    sidebarItemActiveText = Color(0xFFF4F4F5),
    mainBg = Color(0xFF18181B),
    taskText = Color(0xFFE4E4E7),
    taskCompletedText = Color(0xFF71717A),
    taskSubtext = Color(0xFF71717A),
    taskCardBg = Color(0xFF27272A),
    taskDivider = Color(0xFF27272A),
    checkboxBorder = Color(0xFF71717A),
    checkboxChecked = Color(0xFF52525B),
    progressBg = Color(0xFF3F3F46),
    progressFill = Color(0xFFA1A1AA),
    btnPrimary = Color(0xFFF4F4F5),
    btnPrimaryText = Color(0xFF18181B),
    inputBg = Color(0xFF27272A),
    inputBorder = Color(0xFF52525B),
    inputText = Color(0xFFE4E4E7),
    accentColor = Color(0xFFA78BFA),
    badgeBg = Color(0xFF3F3F46),
    badgeText = Color(0xFFA1A1AA),
    cardBg = Color(0xFF18181B),
    isDark = true,
)

val DragonsTheme = ContextThemeColorScheme(
    background = Color(0xFF1C1917),
    headerBg = Color(0xFF1C1917),
    headerBorder = Color(0xFF78350F),
    headerText = Color(0xFFFEF3C7),
    headerSubtext = Color(0xFFF59E0B),
    sidebarBg = Color(0xFF1C1917),
    sidebarLabel = Color(0xFFB45309),
    sidebarItemText = Color(0xFFFBBF24),
    sidebarItemActive = Color(0xFF451A03),
    sidebarItemActiveText = Color(0xFFFEF3C7),
    mainBg = Color(0xFF0C0A09),
    taskText = Color(0xFFFEF3C7),
    taskCompletedText = Color(0xFF92400E),
    taskSubtext = Color(0xFFF59E0B),
    taskCardBg = Color(0xFF1C1917),
    taskDivider = Color(0xFF451A03),
    checkboxBorder = Color(0xFFD97706),
    checkboxChecked = Color(0xFFB45309),
    progressBg = Color(0xFF292524),
    progressFill = Color(0xFFF59E0B),
    btnPrimary = Color(0xFFD97706),
    btnPrimaryText = Color(0xFF0C0A09),
    inputBg = Color(0xFF1C1917),
    inputBorder = Color(0xFF78350F),
    inputText = Color(0xFFFEF3C7),
    accentColor = Color(0xFFF59E0B),
    badgeBg = Color(0xFF451A03),
    badgeText = Color(0xFFFBBF24),
    cardBg = Color(0xFF1C1917),
    isDark = true,
)

val IceDragonsTheme = ContextThemeColorScheme(
    background = Color(0xFF0F172A),
    headerBg = Color(0xFF0F172A),
    headerBorder = Color(0xFF164E63),
    headerText = Color(0xFFE0F2FE),
    headerSubtext = Color(0xFF22D3EE),
    sidebarBg = Color(0xFF0F172A),
    sidebarLabel = Color(0xFF0891B2),
    sidebarItemText = Color(0xFF67E8F9),
    sidebarItemActive = Color(0xFF083344),
    sidebarItemActiveText = Color(0xFFE0F2FE),
    mainBg = Color(0xFF020617),
    taskText = Color(0xFFE0F2FE),
    taskCompletedText = Color(0xFF155E75),
    taskSubtext = Color(0xFF22D3EE),
    taskCardBg = Color(0xFF0F172A),
    taskDivider = Color(0xFF083344),
    checkboxBorder = Color(0xFF0891B2),
    checkboxChecked = Color(0xFF0E7490),
    progressBg = Color(0xFF1E293B),
    progressFill = Color(0xFF22D3EE),
    btnPrimary = Color(0xFF0891B2),
    btnPrimaryText = Color(0xFF020617),
    inputBg = Color(0xFF0F172A),
    inputBorder = Color(0xFF164E63),
    inputText = Color(0xFFE0F2FE),
    accentColor = Color(0xFF38BDF8),
    badgeBg = Color(0xFF083344),
    badgeText = Color(0xFF7DD3FC),
    cardBg = Color(0xFF0C4A6E),
    isDark = true,
)

private val THEME_MAP = mapOf(
    "MINIMALIST" to MinimalistTheme,
    "DESIGN" to DesignTheme,
    "FORMAL" to FormalTheme,
    "NATURE" to NatureTheme,
    "DARK" to DarkTheme,
    "DRAGONS" to DragonsTheme,
    "ICE_DRAGONS" to IceDragonsTheme,
)

fun getContextTheme(theme: String): ContextThemeColorScheme {
    return THEME_MAP[theme] ?: MinimalistTheme
}

data class ThemePreview(
    val key: String,
    val label: String,
    val primaryColor: Color,
    val bgColor: Color,
    val textColor: Color,
)

val THEME_PREVIEWS = listOf(
    ThemePreview("MINIMALIST", "Minimalist", Color(0xFF78716C), Color(0xFFF5F5F5), Color(0xFF1C1917)),
    ThemePreview("DESIGN", "Design", Color(0xFF7C3AED), Color(0xFFF5F3FF), Color(0xFF5B21B6)),
    ThemePreview("FORMAL", "Formal", Color(0xFF475569), Color(0xFFF9FAFB), Color(0xFF0F172A)),
    ThemePreview("NATURE", "Nature", Color(0xFF059669), Color(0xFFF0FDF4), Color(0xFF065F46)),
    ThemePreview("DARK", "Dark", Color(0xFFA78BFA), Color(0xFF18181B), Color(0xFFF4F4F5)),
    ThemePreview("DRAGONS", "Dragons", Color(0xFFF59E0B), Color(0xFF1C1917), Color(0xFFFBBF24)),
    ThemePreview("ICE_DRAGONS", "Ice Dragons", Color(0xFF38BDF8), Color(0xFF0C4A6E), Color(0xFFE0F2FE)),
)
