import {
  Inbox, Zap, FolderOpen, Clock, Lightbulb, BookOpen, Calendar,
  CheckCircle, Tag, Briefcase, Home, Target, Activity, Palette,
  Music, Wallet, ShoppingCart, Plane, Wrench, GraduationCap,
  Dumbbell, Heart, Star, Camera, Coffee, Globe, Headphones,
  Laptop, Map, Phone, Scissors, Smile, Sun, Umbrella, Utensils,
  Bike, Car, Film, Gift, Key, Leaf, Mountain, Sparkles,
} from 'lucide-react';
import type { ComponentType } from 'react';
import type { GtdList } from '../types';

export const GTD_ICONS: Record<GtdList, ComponentType<{ className?: string }>> = {
  INBOX: Inbox,
  NEXT_ACTIONS: Zap,
  PROJECTS: FolderOpen,
  WAITING_FOR: Clock,
  SOMEDAY_MAYBE: Lightbulb,
  REFERENCE: BookOpen,
  CALENDAR: Calendar,
  DONE: CheckCircle,
};

const CATEGORY_ICON_MAP: Record<string, ComponentType<{ className?: string }>> = {
  'book-open': BookOpen,
  'briefcase': Briefcase,
  'home': Home,
  'target': Target,
  'activity': Activity,
  'palette': Palette,
  'music': Music,
  'wallet': Wallet,
  'shopping-cart': ShoppingCart,
  'plane': Plane,
  'wrench': Wrench,
  'graduation-cap': GraduationCap,
  'camera': Camera,
  'coffee': Coffee,
  'globe': Globe,
  'headphones': Headphones,
  'laptop': Laptop,
  'map': Map,
  'phone': Phone,
  'scissors': Scissors,
  'smile': Smile,
  'sun': Sun,
  'umbrella': Umbrella,
  'utensils': Utensils,
  'bike': Bike,
  'car': Car,
  'film': Film,
  'gift': Gift,
  'key': Key,
  'leaf': Leaf,
  'mountain': Mountain,
  'sparkles': Sparkles,
  'dumbbell': Dumbbell,
  'heart': Heart,
  'star': Star,
};

const CONTEXT_ICON_MAP: Record<string, ComponentType<{ className?: string }>> = {
  'briefcase': Briefcase,
  'home': Home,
  'book-open': BookOpen,
  'target': Target,
  'dumbbell': Dumbbell,
  'palette': Palette,
  'music': Music,
  'plane': Plane,
  'lightbulb': Lightbulb,
  'shopping-cart': ShoppingCart,
  'heart': Heart,
  'star': Star,
};

const EMOJI_TO_LUCIDE: Record<string, string> = {
  '\uD83D\uDCDA': 'book-open',
  '\uD83D\uDCBC': 'briefcase',
  '\uD83C\uDFE0': 'home',
  '\uD83C\uDFAF': 'target',
  '\uD83C\uDFC3': 'activity',
  '\uD83C\uDFA8': 'palette',
  '\uD83C\uDFB5': 'music',
  '\uD83D\uDCB0': 'wallet',
  '\uD83D\uDED2': 'shopping-cart',
  '\u2708\uFE0F': 'plane',
  '\uD83D\uDD27': 'wrench',
  '\uD83C\uDF93': 'graduation-cap',
  '\uD83D\uDCF7': 'camera',
  '\u2615': 'coffee',
  '\uD83C\uDF0D': 'globe',
  '\uD83C\uDFA7': 'headphones',
  '\uD83D\uDCBB': 'laptop',
  '\uD83D\uDDFA\uFE0F': 'map',
  '\uD83D\uDCDE': 'phone',
  '\u2702\uFE0F': 'scissors',
  '\uD83D\uDE04': 'smile',
  '\u2600\uFE0F': 'sun',
  '\u2602\uFE0F': 'umbrella',
  '\uD83C\uDF74': 'utensils',
  '\uD83D\uDEB2': 'bike',
  '\uD83D\uDE97': 'car',
  '\uD83C\uDFAC': 'film',
  '\uD83C\uDF81': 'gift',
  '\uD83D\uDD11': 'key',
  '\uD83C\uDF3F': 'leaf',
  '\u26F0\uFE0F': 'mountain',
  '\u2728': 'sparkles',
  '\uD83C\uDFCB\uFE0F': 'dumbbell',
  '\u2764\uFE0F': 'heart',
  '\u2B50': 'star',
  '\uD83D\uDCC1': 'briefcase',
  '\uD83D\uDD27': 'wrench',
  '\uD83C\uDF4E': 'leaf',
  '\uD83D\uDCDD': 'book-open',
  '\uD83C\uDF93': 'graduation-cap',
  '\u2764\uFE0F': 'heart',
};

export function getCategoryIcon(iconKey: string | null | undefined): ComponentType<{ className?: string }> {
  if (!iconKey) return Tag;
  const resolved = CATEGORY_ICON_MAP[iconKey] ?? CATEGORY_ICON_MAP[EMOJI_TO_LUCIDE[iconKey] ?? ''];
  return resolved ?? Tag;
}

export function getContextIcon(iconKey: string | null | undefined): ComponentType<{ className?: string }> {
  if (!iconKey) return Briefcase;
  return CONTEXT_ICON_MAP[iconKey] ?? Briefcase;
}

export const PRESET_CATEGORY_ICONS: { key: string; Icon: ComponentType<{ className?: string }>; label: string }[] = [
  { key: 'book-open', Icon: BookOpen, label: 'Books' },
  { key: 'briefcase', Icon: Briefcase, label: 'Work' },
  { key: 'home', Icon: Home, label: 'Home' },
  { key: 'target', Icon: Target, label: 'Goals' },
  { key: 'activity', Icon: Activity, label: 'Fitness' },
  { key: 'palette', Icon: Palette, label: 'Art' },
  { key: 'music', Icon: Music, label: 'Music' },
  { key: 'wallet', Icon: Wallet, label: 'Finance' },
  { key: 'shopping-cart', Icon: ShoppingCart, label: 'Shopping' },
  { key: 'plane', Icon: Plane, label: 'Travel' },
  { key: 'wrench', Icon: Wrench, label: 'Tools' },
  { key: 'graduation-cap', Icon: GraduationCap, label: 'Study' },
  { key: 'camera', Icon: Camera, label: 'Photo' },
  { key: 'coffee', Icon: Coffee, label: 'Drinks' },
  { key: 'globe', Icon: Globe, label: 'World' },
  { key: 'headphones', Icon: Headphones, label: 'Audio' },
  { key: 'laptop', Icon: Laptop, label: 'Tech' },
  { key: 'map', Icon: Map, label: 'Places' },
  { key: 'phone', Icon: Phone, label: 'Calls' },
  { key: 'scissors', Icon: Scissors, label: 'Craft' },
  { key: 'smile', Icon: Smile, label: 'Fun' },
  { key: 'sun', Icon: Sun, label: 'Morning' },
  { key: 'umbrella', Icon: Umbrella, label: 'Weather' },
  { key: 'utensils', Icon: Utensils, label: 'Food' },
  { key: 'bike', Icon: Bike, label: 'Cycling' },
  { key: 'car', Icon: Car, label: 'Drive' },
  { key: 'film', Icon: Film, label: 'Movies' },
  { key: 'gift', Icon: Gift, label: 'Gifts' },
  { key: 'key', Icon: Key, label: 'Keys' },
  { key: 'leaf', Icon: Leaf, label: 'Nature' },
  { key: 'mountain', Icon: Mountain, label: 'Outdoor' },
  { key: 'sparkles', Icon: Sparkles, label: 'Magic' },
  { key: 'dumbbell', Icon: Dumbbell, label: 'Gym' },
  { key: 'heart', Icon: Heart, label: 'Health' },
  { key: 'star', Icon: Star, label: 'Favorite' },
];

export const PRESET_CONTEXT_ICONS: { key: string; Icon: ComponentType<{ className?: string }>; label: string }[] = [
  { key: 'briefcase', Icon: Briefcase, label: 'Work' },
  { key: 'home', Icon: Home, label: 'Home' },
  { key: 'book-open', Icon: BookOpen, label: 'Books' },
  { key: 'target', Icon: Target, label: 'Goals' },
  { key: 'dumbbell', Icon: Dumbbell, label: 'Fitness' },
  { key: 'palette', Icon: Palette, label: 'Art' },
  { key: 'music', Icon: Music, label: 'Music' },
  { key: 'plane', Icon: Plane, label: 'Travel' },
  { key: 'lightbulb', Icon: Lightbulb, label: 'Ideas' },
  { key: 'shopping-cart', Icon: ShoppingCart, label: 'Shopping' },
  { key: 'heart', Icon: Heart, label: 'Health' },
  { key: 'star', Icon: Star, label: 'Favorites' },
];
