import type { ContextTheme } from '../types';

export interface ThemeColors {
  bg: string;
  headerBg: string;
  headerBorder: string;
  headerText: string;
  headerSubtext: string;
  sidebarBg: string;
  sidebarBorder: string;
  sidebarLabel: string;
  sidebarItemText: string;
  sidebarItemHover: string;
  sidebarItemActive: string;
  sidebarItemActiveText: string;
  sidebarBadge: string;
  sidebarBadgeActive: string;
  sidebarDivider: string;
  mainBg: string;
  listHeaderBorder: string;
  listHeaderText: string;
  listCountBadge: string;
  taskText: string;
  taskCompletedText: string;
  taskSubtext: string;
  taskHover: string;
  taskSelected: string;
  taskDivider: string;
  checkbox: string;
  checkboxChecked: string;
  progressBg: string;
  progressFill: string;
  inputBorder: string;
  inputFocus: string;
  inputBg: string;
  inputText: string;
  inputPlaceholder: string;
  btnPrimary: string;
  btnPrimaryHover: string;
  btnPrimaryText: string;
  labelText: string;
  panelBg: string;
  panelBorder: string;
  emptyIcon: string;
  emptyText: string;
  dropTargetBg: string;
  dropTargetRing: string;
  borderRadius: string;
  borderRadiusLg: string;
  shadow: string;
  shadowLg: string;
  fontFamily: string;
  headerFont: string;
  spacing: string;
  labelStyle: string;
  decorativeBorder: string;
  cardStyle: string;
  bgPattern: string;
  checkboxRadius: string;
  checkboxSize: string;
  checkboxExtra: string;
  progressRadius: string;
  progressHeight: string;
  progressHeightSm: string;
  progressExtra: string;
  headerStyle: string;
  headerTitleSize: string;
  transitionSpeed: string;
  // TASK-053: unique decorative elements per theme
  sidebarSectionUnderline: string;
  badgeFont: string;
  taskHoverIndicator: string;
  sidebarDividerStyle: string;
  addBtnExtra: string;
  sidebarActiveStyle: string;
  taskNumbering: boolean;
  taskCompletedStamp: boolean;
  headerAccent: string;
  taskActiveUnderline: string;
  sidebarTopBorder: string;
  neonDotIndicator: boolean;
  scanlineOverlay: boolean;
  glowText: string;
  animatedBorder: boolean;
  breathingBg: boolean;
  leafIcon: boolean;
  blobBadge: boolean;
  floatingShadow: string;
  pulseAddBtn: boolean;
  dropCapProject: boolean;
  // TASK-054: DRAGONS theme unique elements
  fireAnimatedBorder: boolean;
  emberHover: boolean;
  clawMarks: boolean;
  moltenText: string;
  emberDotIndicator: boolean;
  dragonsBreathingBg: boolean;
  dragonsForgeStamp: boolean;
  // ICE_DRAGONS theme unique elements
  iceAnimatedBorder: boolean;
  frostHover: boolean;
  iceClawMarks: boolean;
  frozenText: string;
  iceDotIndicator: boolean;
  iceBreathingBg: boolean;
  iceForgeStamp: boolean;
  colorScheme: 'light' | 'dark';
}

const MINIMALIST: ThemeColors = {
  bg: 'bg-stone-50',
  headerBg: 'bg-white',
  headerBorder: 'border-stone-200',
  headerText: 'text-stone-900',
  headerSubtext: 'text-stone-400',
  sidebarBg: 'bg-white',
  sidebarBorder: 'border-stone-200',
  sidebarLabel: 'text-stone-400',
  sidebarItemText: 'text-stone-600',
  sidebarItemHover: 'hover:bg-stone-50 hover:text-stone-900',
  sidebarItemActive: 'bg-stone-100',
  sidebarItemActiveText: 'font-medium text-stone-900',
  sidebarBadge: 'bg-stone-100 text-stone-500',
  sidebarBadgeActive: 'bg-stone-200 text-stone-700',
  sidebarDivider: 'border-stone-100',
  mainBg: 'bg-white',
  listHeaderBorder: 'border-stone-200',
  listHeaderText: 'text-stone-900',
  listCountBadge: 'bg-stone-100 text-stone-500',
  taskText: 'text-stone-800',
  taskCompletedText: 'text-stone-400',
  taskSubtext: 'text-stone-400',
  taskHover: 'hover:bg-stone-50/50',
  taskSelected: 'bg-stone-50',
  taskDivider: 'divide-stone-100',
  checkbox: 'border-stone-300 hover:border-stone-500',
  checkboxChecked: 'border-stone-300 bg-stone-200 text-stone-500',
  progressBg: 'bg-stone-200',
  progressFill: 'bg-stone-500',
  inputBorder: 'border-stone-200',
  inputFocus: 'focus:border-stone-400 focus:ring-stone-400/30',
  inputBg: 'bg-white',
  inputText: 'text-stone-800',
  inputPlaceholder: 'placeholder:text-stone-400',
  btnPrimary: 'bg-stone-900',
  btnPrimaryHover: 'hover:bg-stone-800',
  btnPrimaryText: 'text-white',
  labelText: 'text-stone-400',
  panelBg: 'bg-white',
  panelBorder: 'border-stone-200',
  emptyIcon: 'opacity-30',
  emptyText: 'text-stone-400',
  dropTargetBg: 'bg-blue-50',
  dropTargetRing: 'ring-1 ring-blue-300',
  borderRadius: 'rounded-none',
  borderRadiusLg: 'rounded-sm',
  shadow: 'shadow-none',
  shadowLg: 'shadow-none',
  fontFamily: 'font-sans',
  headerFont: 'font-sans',
  spacing: 'px-3 py-2',
  labelStyle: '',
  decorativeBorder: 'border',
  cardStyle: 'border',
  bgPattern: '',
  checkboxRadius: 'rounded-none',
  checkboxSize: 'h-[18px] w-[18px]',
  checkboxExtra: '',
  progressRadius: 'rounded-none',
  progressHeight: 'h-1',
  progressHeightSm: 'h-1',
  progressExtra: '',
  headerStyle: '',
  headerTitleSize: 'text-base',
  transitionSpeed: 'duration-75',
  sidebarSectionUnderline: 'border-b border-stone-200',
  badgeFont: 'font-mono',
  taskHoverIndicator: 'theme-minimalist-hover-indicator',
  sidebarDividerStyle: 'gap',
  addBtnExtra: '',
  sidebarActiveStyle: '',
  taskNumbering: false,
  taskCompletedStamp: false,
  headerAccent: '',
  taskActiveUnderline: '',
  sidebarTopBorder: '',
  neonDotIndicator: false,
  scanlineOverlay: false,
  glowText: '',
  animatedBorder: false,
  breathingBg: false,
  leafIcon: false,
  blobBadge: false,
  floatingShadow: '',
  pulseAddBtn: false,
  dropCapProject: false,
  fireAnimatedBorder: false,
  emberHover: false,
  clawMarks: false,
  moltenText: '',
  emberDotIndicator: false,
  dragonsBreathingBg: false,
  dragonsForgeStamp: false,
  iceAnimatedBorder: false,
  frostHover: false,
  iceClawMarks: false,
  frozenText: '',
  iceDotIndicator: false,
  iceBreathingBg: false,
  iceForgeStamp: false,
  colorScheme: 'light',
};

const DESIGN: ThemeColors = {
  bg: 'bg-violet-50/40',
  headerBg: 'bg-white',
  headerBorder: 'border-violet-100',
  headerText: 'text-violet-900',
  headerSubtext: 'text-violet-400',
  sidebarBg: 'bg-violet-50/30',
  sidebarBorder: 'border-violet-100',
  sidebarLabel: 'text-violet-400',
  sidebarItemText: 'text-violet-600',
  sidebarItemHover: 'hover:bg-violet-100/50 hover:text-violet-900',
  sidebarItemActive: 'bg-violet-100',
  sidebarItemActiveText: 'font-medium text-violet-900',
  sidebarBadge: 'bg-violet-100 text-violet-500',
  sidebarBadgeActive: 'theme-design-pill-badge',
  sidebarDivider: 'border-violet-100',
  mainBg: 'bg-white',
  listHeaderBorder: 'border-violet-100',
  listHeaderText: 'text-violet-900',
  listCountBadge: 'bg-violet-100 text-violet-500',
  taskText: 'text-violet-800',
  taskCompletedText: 'text-violet-300',
  taskSubtext: 'text-violet-400',
  taskHover: 'hover:bg-violet-50/50',
  taskSelected: 'bg-violet-50',
  taskDivider: 'divide-violet-100',
  checkbox: 'border-violet-300 hover:border-violet-500',
  checkboxChecked: 'border-violet-300 bg-violet-200 text-violet-500',
  progressBg: 'bg-violet-200',
  progressFill: 'bg-violet-500',
  inputBorder: 'border-violet-200',
  inputFocus: 'focus:border-violet-400 focus:ring-violet-400/30',
  inputBg: 'bg-white',
  inputText: 'text-violet-800',
  inputPlaceholder: 'placeholder:text-violet-400',
  btnPrimary: 'bg-violet-600',
  btnPrimaryHover: 'hover:bg-violet-700',
  btnPrimaryText: 'text-white',
  labelText: 'text-violet-400',
  panelBg: 'bg-white',
  panelBorder: 'border-violet-100',
  emptyIcon: 'opacity-30',
  emptyText: 'text-violet-400',
  dropTargetBg: 'bg-violet-50',
  dropTargetRing: 'ring-1 ring-violet-300',
  borderRadius: 'rounded-2xl',
  borderRadiusLg: 'rounded-3xl',
  shadow: 'shadow-lg',
  shadowLg: 'shadow-xl',
  fontFamily: 'font-sans',
  headerFont: 'font-sans',
  spacing: 'px-5 py-3',
  labelStyle: 'tracking-wide',
  decorativeBorder: 'border-2',
  cardStyle: 'border-2 bg-gradient-to-br from-white to-violet-50/50',
  bgPattern: 'theme-bg-dots',
  checkboxRadius: 'rounded-full',
  checkboxSize: 'h-5 w-5',
  checkboxExtra: 'hover:ring-2 hover:ring-violet-200/50',
  progressRadius: 'rounded-full',
  progressHeight: 'h-2.5',
  progressHeightSm: 'h-1.5',
  progressExtra: '',
  headerStyle: 'bg-gradient-to-r from-violet-50 to-white',
  headerTitleSize: 'text-lg',
  transitionSpeed: 'duration-300 ease-out',
  sidebarSectionUnderline: '',
  badgeFont: '',
  taskHoverIndicator: '',
  sidebarDividerStyle: 'theme-design-gradient-divider',
  addBtnExtra: 'theme-design-pulse',
  sidebarActiveStyle: 'theme-design-notch',
  taskNumbering: false,
  taskCompletedStamp: false,
  headerAccent: '',
  taskActiveUnderline: '',
  sidebarTopBorder: '',
  neonDotIndicator: false,
  scanlineOverlay: false,
  glowText: '',
  animatedBorder: false,
  breathingBg: false,
  leafIcon: false,
  blobBadge: false,
  floatingShadow: 'theme-design-float',
  pulseAddBtn: true,
  dropCapProject: false,
  fireAnimatedBorder: false,
  emberHover: false,
  clawMarks: false,
  moltenText: '',
  emberDotIndicator: false,
  dragonsBreathingBg: false,
  dragonsForgeStamp: false,
  iceAnimatedBorder: false,
  frostHover: false,
  iceClawMarks: false,
  frozenText: '',
  iceDotIndicator: false,
  iceBreathingBg: false,
  iceForgeStamp: false,
  colorScheme: 'light',
};

const FORMAL: ThemeColors = {
  bg: 'bg-slate-50',
  headerBg: 'bg-white',
  headerBorder: 'border-slate-200',
  headerText: 'text-slate-900',
  headerSubtext: 'text-slate-400',
  sidebarBg: 'bg-slate-50/60',
  sidebarBorder: 'border-slate-200',
  sidebarLabel: 'text-slate-400',
  sidebarItemText: 'text-slate-600',
  sidebarItemHover: 'hover:bg-slate-100/60 hover:text-slate-900',
  sidebarItemActive: 'bg-slate-100',
  sidebarItemActiveText: 'font-medium text-slate-900',
  sidebarBadge: 'bg-slate-100 text-slate-500',
  sidebarBadgeActive: 'bg-slate-200 text-slate-700',
  sidebarDivider: 'border-slate-100',
  mainBg: 'bg-white',
  listHeaderBorder: 'border-slate-200',
  listHeaderText: 'text-slate-900',
  listCountBadge: 'bg-slate-100 text-slate-500',
  taskText: 'text-slate-800',
  taskCompletedText: 'text-slate-400',
  taskSubtext: 'text-slate-400',
  taskHover: 'hover:bg-slate-50/50',
  taskSelected: 'bg-slate-50',
  taskDivider: 'divide-slate-100',
  checkbox: 'border-slate-300 hover:border-slate-500',
  checkboxChecked: 'border-slate-300 bg-slate-200 text-slate-500',
  progressBg: 'bg-slate-200',
  progressFill: 'bg-slate-500',
  inputBorder: 'border-slate-200',
  inputFocus: 'focus:border-slate-400 focus:ring-slate-400/30',
  inputBg: 'bg-white',
  inputText: 'text-slate-800',
  inputPlaceholder: 'placeholder:text-slate-400',
  btnPrimary: 'bg-slate-800',
  btnPrimaryHover: 'hover:bg-slate-900',
  btnPrimaryText: 'text-white',
  labelText: 'text-slate-400',
  panelBg: 'bg-white',
  panelBorder: 'border-slate-200',
  emptyIcon: 'opacity-30',
  emptyText: 'text-slate-400',
  dropTargetBg: 'bg-blue-50',
  dropTargetRing: 'ring-1 ring-blue-300',
  borderRadius: 'rounded-md',
  borderRadiusLg: 'rounded-lg',
  shadow: 'shadow-sm',
  shadowLg: 'shadow-md',
  fontFamily: 'font-sans',
  headerFont: 'font-serif',
  spacing: 'px-4 py-3',
  labelStyle: 'uppercase tracking-wider',
  decorativeBorder: 'border-double border-2',
  cardStyle: 'border-double border-2',
  bgPattern: 'theme-bg-lines',
  checkboxRadius: 'rounded-sm',
  checkboxSize: 'h-[18px] w-[18px]',
  checkboxExtra: 'border-double',
  progressRadius: 'rounded-sm',
  progressHeight: 'h-1.5',
  progressHeightSm: 'h-1',
  progressExtra: '',
  headerStyle: 'border-b-2',
  headerTitleSize: 'text-sm',
  transitionSpeed: 'duration-150',
  sidebarSectionUnderline: '',
  badgeFont: '',
  taskHoverIndicator: '',
  sidebarDividerStyle: '',
  addBtnExtra: '',
  sidebarActiveStyle: '',
  taskNumbering: true,
  taskCompletedStamp: true,
  headerAccent: 'theme-formal-rule-line',
  taskActiveUnderline: '',
  sidebarTopBorder: '',
  neonDotIndicator: false,
  scanlineOverlay: false,
  glowText: '',
  animatedBorder: false,
  breathingBg: false,
  leafIcon: false,
  blobBadge: false,
  floatingShadow: '',
  pulseAddBtn: false,
  dropCapProject: true,
  fireAnimatedBorder: false,
  emberHover: false,
  clawMarks: false,
  moltenText: '',
  emberDotIndicator: false,
  dragonsBreathingBg: false,
  dragonsForgeStamp: false,
  iceAnimatedBorder: false,
  frostHover: false,
  iceClawMarks: false,
  frozenText: '',
  iceDotIndicator: false,
  iceBreathingBg: false,
  iceForgeStamp: false,
  colorScheme: 'light',
};

const NATURE: ThemeColors = {
  bg: 'bg-emerald-50/40',
  headerBg: 'bg-white',
  headerBorder: 'border-emerald-100',
  headerText: 'text-emerald-900',
  headerSubtext: 'text-emerald-400',
  sidebarBg: 'bg-emerald-50/30',
  sidebarBorder: 'border-emerald-100',
  sidebarLabel: 'text-emerald-500',
  sidebarItemText: 'text-emerald-700',
  sidebarItemHover: 'hover:bg-emerald-100/40 hover:text-emerald-900',
  sidebarItemActive: 'bg-emerald-100',
  sidebarItemActiveText: 'font-medium text-emerald-900',
  sidebarBadge: 'bg-emerald-100 text-emerald-600',
  sidebarBadgeActive: 'bg-emerald-200 text-emerald-700',
  sidebarDivider: 'border-emerald-100',
  mainBg: 'bg-white',
  listHeaderBorder: 'border-emerald-100',
  listHeaderText: 'text-emerald-900',
  listCountBadge: 'bg-emerald-100 text-emerald-600',
  taskText: 'text-emerald-800',
  taskCompletedText: 'text-emerald-300',
  taskSubtext: 'text-emerald-400',
  taskHover: 'hover:bg-emerald-50/50',
  taskSelected: 'bg-emerald-50',
  taskDivider: 'divide-emerald-100',
  checkbox: 'border-emerald-300 hover:border-emerald-500',
  checkboxChecked: 'border-emerald-300 bg-emerald-200 text-emerald-500',
  progressBg: 'bg-emerald-200',
  progressFill: 'bg-emerald-500',
  inputBorder: 'border-emerald-200',
  inputFocus: 'focus:border-emerald-400 focus:ring-emerald-400/30',
  inputBg: 'bg-white',
  inputText: 'text-emerald-800',
  inputPlaceholder: 'placeholder:text-emerald-400',
  btnPrimary: 'bg-emerald-600',
  btnPrimaryHover: 'hover:bg-emerald-700',
  btnPrimaryText: 'text-white',
  labelText: 'text-emerald-500',
  panelBg: 'bg-white',
  panelBorder: 'border-emerald-100',
  emptyIcon: 'opacity-30',
  emptyText: 'text-emerald-400',
  dropTargetBg: 'bg-emerald-50',
  dropTargetRing: 'ring-1 ring-emerald-300',
  borderRadius: 'rounded-xl',
  borderRadiusLg: 'rounded-2xl',
  shadow: 'shadow-md shadow-emerald-100/50',
  shadowLg: 'shadow-lg shadow-emerald-100/50',
  fontFamily: 'font-sans',
  headerFont: 'font-sans',
  spacing: 'px-5 py-3',
  labelStyle: '',
  decorativeBorder: 'border',
  cardStyle: 'border',
  bgPattern: 'theme-bg-gradient',
  checkboxRadius: 'rounded-md',
  checkboxSize: 'h-[18px] w-[18px]',
  checkboxExtra: 'hover:ring-1 hover:ring-emerald-200/30',
  progressRadius: 'rounded-xl',
  progressHeight: 'h-2',
  progressHeightSm: 'h-1.5',
  progressExtra: '',
  headerStyle: 'bg-gradient-to-b from-emerald-50/60 to-transparent',
  headerTitleSize: 'text-base',
  transitionSpeed: 'duration-300 ease-in-out',
  sidebarSectionUnderline: '',
  badgeFont: '',
  taskHoverIndicator: '',
  sidebarDividerStyle: '',
  addBtnExtra: '',
  sidebarActiveStyle: '',
  taskNumbering: false,
  taskCompletedStamp: false,
  headerAccent: '',
  taskActiveUnderline: 'theme-nature-underline',
  sidebarTopBorder: 'theme-nature-wavy-top',
  neonDotIndicator: false,
  scanlineOverlay: false,
  glowText: '',
  animatedBorder: false,
  breathingBg: true,
  leafIcon: true,
  blobBadge: true,
  floatingShadow: '',
  pulseAddBtn: false,
  dropCapProject: false,
  fireAnimatedBorder: false,
  emberHover: false,
  clawMarks: false,
  moltenText: '',
  emberDotIndicator: false,
  dragonsBreathingBg: false,
  dragonsForgeStamp: false,
  iceAnimatedBorder: false,
  frostHover: false,
  iceClawMarks: false,
  frozenText: '',
  iceDotIndicator: false,
  iceBreathingBg: false,
  iceForgeStamp: false,
  colorScheme: 'light',
};

const DARK: ThemeColors = {
  bg: 'bg-zinc-900',
  headerBg: 'bg-zinc-800',
  headerBorder: 'border-zinc-700',
  headerText: 'text-zinc-100',
  headerSubtext: 'text-zinc-400',
  sidebarBg: 'bg-zinc-800',
  sidebarBorder: 'border-zinc-700',
  sidebarLabel: 'text-zinc-500',
  sidebarItemText: 'text-zinc-400',
  sidebarItemHover: 'hover:bg-zinc-700 hover:text-zinc-200',
  sidebarItemActive: 'bg-zinc-700',
  sidebarItemActiveText: 'font-medium text-zinc-100',
  sidebarBadge: 'bg-zinc-700 text-zinc-400',
  sidebarBadgeActive: 'bg-zinc-600 text-zinc-200',
  sidebarDivider: 'border-zinc-700',
  mainBg: 'bg-zinc-900',
  listHeaderBorder: 'border-zinc-700',
  listHeaderText: 'text-zinc-100',
  listCountBadge: 'bg-zinc-700 text-zinc-300',
  taskText: 'text-zinc-200',
  taskCompletedText: 'text-zinc-500',
  taskSubtext: 'text-zinc-500',
  taskHover: 'hover:bg-zinc-800/60',
  taskSelected: 'bg-zinc-800',
  taskDivider: 'divide-zinc-800',
  checkbox: 'border-zinc-500 hover:border-zinc-300',
  checkboxChecked: 'border-zinc-500 bg-zinc-600 text-zinc-300',
  progressBg: 'bg-zinc-700',
  progressFill: 'bg-zinc-400',
  inputBorder: 'border-zinc-600',
  inputFocus: 'focus:border-zinc-400 focus:ring-zinc-400/30',
  inputBg: 'bg-zinc-800',
  inputText: 'text-zinc-200',
  inputPlaceholder: 'placeholder:text-zinc-500',
  btnPrimary: 'bg-zinc-100',
  btnPrimaryHover: 'hover:bg-white',
  btnPrimaryText: 'text-zinc-900',
  labelText: 'text-zinc-500',
  panelBg: 'bg-zinc-800',
  panelBorder: 'border-zinc-700',
  emptyIcon: 'opacity-20',
  emptyText: 'text-zinc-500',
  dropTargetBg: 'bg-zinc-700',
  dropTargetRing: 'ring-1 ring-zinc-500',
  borderRadius: 'rounded-lg',
  borderRadiusLg: 'rounded-xl',
  shadow: 'shadow-lg shadow-black/30',
  shadowLg: 'shadow-xl shadow-black/40',
  fontFamily: 'font-sans',
  headerFont: 'font-sans',
  spacing: 'px-4 py-3',
  labelStyle: '',
  decorativeBorder: 'border',
  cardStyle: 'border backdrop-blur-md bg-zinc-800/80',
  bgPattern: 'theme-bg-glow',
  checkboxRadius: 'rounded',
  checkboxSize: 'h-[18px] w-[18px]',
  checkboxExtra: 'hover:shadow-sm hover:shadow-zinc-500/20',
  progressRadius: 'rounded-lg',
  progressHeight: 'h-2',
  progressHeightSm: 'h-1.5',
  progressExtra: '',
  headerStyle: 'shadow-[0_1px_8px_rgba(139,92,246,0.15)]',
  headerTitleSize: 'text-base',
  transitionSpeed: 'duration-100 ease-linear',
  sidebarSectionUnderline: '',
  badgeFont: '',
  taskHoverIndicator: '',
  sidebarDividerStyle: '',
  addBtnExtra: '',
  sidebarActiveStyle: 'theme-dark-neon-glow',
  taskNumbering: false,
  taskCompletedStamp: false,
  headerAccent: '',
  taskActiveUnderline: '',
  sidebarTopBorder: '',
  neonDotIndicator: true,
  scanlineOverlay: true,
  glowText: 'theme-dark-glow-text',
  animatedBorder: true,
  breathingBg: false,
  leafIcon: false,
  blobBadge: false,
  floatingShadow: '',
  pulseAddBtn: false,
  dropCapProject: false,
  fireAnimatedBorder: false,
  emberHover: false,
  clawMarks: false,
  moltenText: '',
  emberDotIndicator: false,
  dragonsBreathingBg: false,
  dragonsForgeStamp: false,
  iceAnimatedBorder: false,
  frostHover: false,
  iceClawMarks: false,
  frozenText: '',
  iceDotIndicator: false,
  iceBreathingBg: false,
  iceForgeStamp: false,
  colorScheme: 'dark',
};

const DRAGONS: ThemeColors = {
  bg: 'bg-stone-900',
  headerBg: 'bg-stone-900',
  headerBorder: 'border-amber-900/50',
  headerText: 'text-amber-100',
  headerSubtext: 'text-amber-500/70',
  sidebarBg: 'bg-stone-900',
  sidebarBorder: 'border-amber-900/40',
  sidebarLabel: 'text-amber-600/60',
  sidebarItemText: 'text-amber-300/70',
  sidebarItemHover: 'hover:bg-amber-950/50 hover:text-amber-200',
  sidebarItemActive: 'bg-amber-950/60',
  sidebarItemActiveText: 'font-medium text-amber-100',
  sidebarBadge: 'bg-amber-950/50 text-amber-400/70',
  sidebarBadgeActive: 'bg-amber-900/50 text-amber-200',
  sidebarDivider: 'border-amber-900/30',
  mainBg: 'bg-stone-950',
  listHeaderBorder: 'border-amber-900/40',
  listHeaderText: 'text-amber-100',
  listCountBadge: 'bg-amber-950/50 text-amber-300',
  taskText: 'text-amber-100',
  taskCompletedText: 'text-amber-600/40',
  taskSubtext: 'text-amber-500/60',
  taskHover: 'hover:bg-amber-950/30',
  taskSelected: 'bg-amber-950/40',
  taskDivider: 'divide-amber-900/20',
  checkbox: 'border-amber-600/50 hover:border-amber-400',
  checkboxChecked: 'border-amber-500 bg-amber-600 text-stone-950',
  progressBg: 'bg-stone-800',
  progressFill: 'theme-dragons-fire-progress',
  inputBorder: 'border-amber-800/40',
  inputFocus: 'focus:border-amber-500 focus:ring-amber-500/20',
  inputBg: 'bg-stone-900',
  inputText: 'text-amber-100',
  inputPlaceholder: 'placeholder:text-amber-700/50',
  btnPrimary: 'bg-amber-600',
  btnPrimaryHover: 'hover:bg-amber-500',
  btnPrimaryText: 'text-stone-950',
  labelText: 'text-amber-600/60',
  panelBg: 'bg-stone-900',
  panelBorder: 'border-amber-900/40',
  emptyIcon: 'opacity-20',
  emptyText: 'text-amber-700/50',
  dropTargetBg: 'bg-amber-950/40',
  dropTargetRing: 'ring-1 ring-amber-600/40',
  borderRadius: 'rounded-lg',
  borderRadiusLg: 'rounded-xl',
  shadow: 'shadow-lg shadow-amber-950/40',
  shadowLg: 'shadow-xl shadow-amber-950/50',
  fontFamily: 'font-sans',
  headerFont: 'font-serif',
  spacing: 'px-4 py-3',
  labelStyle: '',
  decorativeBorder: 'border',
  cardStyle: 'border border-amber-900/40 bg-stone-900/90',
  bgPattern: 'theme-bg-scales',
  checkboxRadius: 'rounded',
  checkboxSize: 'h-[18px] w-[18px]',
  checkboxExtra: 'hover:shadow-sm hover:shadow-amber-600/20',
  progressRadius: 'rounded-lg',
  progressHeight: 'h-2',
  progressHeightSm: 'h-1.5',
  progressExtra: 'shadow-[0_0_6px_rgba(217,119,6,0.3)]',
  headerStyle: 'theme-dragons-flame-header',
  headerTitleSize: 'text-base',
  transitionSpeed: 'duration-150 ease-out',
  sidebarSectionUnderline: '',
  badgeFont: 'font-serif',
  taskHoverIndicator: 'theme-dragons-ember-hover',
  sidebarDividerStyle: 'theme-dragons-claw-marks',
  addBtnExtra: '',
  sidebarActiveStyle: 'theme-dragons-fire-glow',
  taskNumbering: false,
  taskCompletedStamp: false,
  headerAccent: '',
  taskActiveUnderline: 'theme-dragons-gold-underline',
  sidebarTopBorder: '',
  neonDotIndicator: false,
  scanlineOverlay: false,
  glowText: '',
  animatedBorder: false,
  breathingBg: false,
  leafIcon: false,
  blobBadge: false,
  floatingShadow: '',
  pulseAddBtn: false,
  dropCapProject: false,
  fireAnimatedBorder: true,
  emberHover: true,
  clawMarks: true,
  moltenText: 'theme-dragons-molten-text',
  emberDotIndicator: true,
  dragonsBreathingBg: true,
  dragonsForgeStamp: true,
  iceAnimatedBorder: false,
  frostHover: false,
  iceClawMarks: false,
  frozenText: '',
  iceDotIndicator: false,
  iceBreathingBg: false,
  iceForgeStamp: false,
  colorScheme: 'dark',
};

const ICE_DRAGONS: ThemeColors = {
  bg: 'bg-slate-900',
  headerBg: 'bg-slate-900',
  headerBorder: 'border-cyan-900/50',
  headerText: 'text-cyan-100',
  headerSubtext: 'text-cyan-500/70',
  sidebarBg: 'bg-slate-900',
  sidebarBorder: 'border-cyan-900/40',
  sidebarLabel: 'text-cyan-600/60',
  sidebarItemText: 'text-cyan-300/70',
  sidebarItemHover: 'hover:bg-cyan-950/50 hover:text-cyan-200',
  sidebarItemActive: 'bg-cyan-950/60',
  sidebarItemActiveText: 'font-medium text-cyan-100',
  sidebarBadge: 'bg-cyan-950/50 text-cyan-400/70',
  sidebarBadgeActive: 'bg-cyan-900/50 text-cyan-200',
  sidebarDivider: 'border-cyan-900/30',
  mainBg: 'bg-slate-950',
  listHeaderBorder: 'border-cyan-900/40',
  listHeaderText: 'text-cyan-100',
  listCountBadge: 'bg-cyan-950/50 text-cyan-300',
  taskText: 'text-cyan-100',
  taskCompletedText: 'text-cyan-600/40',
  taskSubtext: 'text-cyan-500/60',
  taskHover: 'hover:bg-cyan-950/30',
  taskSelected: 'bg-cyan-950/40',
  taskDivider: 'divide-cyan-900/20',
  checkbox: 'border-cyan-600/50 hover:border-cyan-400',
  checkboxChecked: 'border-cyan-500 bg-cyan-600 text-slate-950',
  progressBg: 'bg-slate-800',
  progressFill: 'theme-ice-dragons-frost-progress',
  inputBorder: 'border-cyan-800/40',
  inputFocus: 'focus:border-cyan-500 focus:ring-cyan-500/20',
  inputBg: 'bg-slate-900',
  inputText: 'text-cyan-100',
  inputPlaceholder: 'placeholder:text-cyan-700/50',
  btnPrimary: 'bg-cyan-600',
  btnPrimaryHover: 'hover:bg-cyan-500',
  btnPrimaryText: 'text-slate-950',
  labelText: 'text-cyan-600/60',
  panelBg: 'bg-slate-900',
  panelBorder: 'border-cyan-900/40',
  emptyIcon: 'opacity-20',
  emptyText: 'text-cyan-700/50',
  dropTargetBg: 'bg-cyan-950/40',
  dropTargetRing: 'ring-1 ring-cyan-600/40',
  borderRadius: 'rounded-lg',
  borderRadiusLg: 'rounded-xl',
  shadow: 'shadow-lg shadow-cyan-950/40',
  shadowLg: 'shadow-xl shadow-cyan-950/50',
  fontFamily: 'font-sans',
  headerFont: 'font-serif',
  spacing: 'px-4 py-3',
  labelStyle: '',
  decorativeBorder: 'border',
  cardStyle: 'border border-cyan-900/40 bg-slate-900/90',
  bgPattern: 'theme-bg-frost-scales',
  checkboxRadius: 'rounded',
  checkboxSize: 'h-[18px] w-[18px]',
  checkboxExtra: 'hover:shadow-sm hover:shadow-cyan-600/20',
  progressRadius: 'rounded-lg',
  progressHeight: 'h-2',
  progressHeightSm: 'h-1.5',
  progressExtra: 'shadow-[0_0_6px_rgba(34,211,238,0.3)]',
  headerStyle: 'theme-ice-dragons-frost-header',
  headerTitleSize: 'text-base',
  transitionSpeed: 'duration-150 ease-out',
  sidebarSectionUnderline: '',
  badgeFont: 'font-serif',
  taskHoverIndicator: 'theme-ice-dragons-frost-hover',
  sidebarDividerStyle: 'theme-ice-dragons-claw-marks',
  addBtnExtra: '',
  sidebarActiveStyle: 'theme-ice-dragons-frost-glow',
  taskNumbering: false,
  taskCompletedStamp: false,
  headerAccent: '',
  taskActiveUnderline: 'theme-ice-dragons-ice-underline',
  sidebarTopBorder: '',
  neonDotIndicator: false,
  scanlineOverlay: false,
  glowText: '',
  animatedBorder: false,
  breathingBg: false,
  leafIcon: false,
  blobBadge: false,
  floatingShadow: '',
  pulseAddBtn: false,
  dropCapProject: false,
  fireAnimatedBorder: false,
  emberHover: false,
  clawMarks: false,
  moltenText: '',
  emberDotIndicator: false,
  dragonsBreathingBg: false,
  dragonsForgeStamp: false,
  iceAnimatedBorder: true,
  frostHover: true,
  iceClawMarks: true,
  frozenText: 'theme-ice-dragons-frozen-text',
  iceDotIndicator: true,
  iceBreathingBg: true,
  iceForgeStamp: true,
  colorScheme: 'dark',
};

const THEME_MAP: Record<ContextTheme, ThemeColors> = {
  MINIMALIST,
  DESIGN,
  FORMAL,
  NATURE,
  DARK,
  DRAGONS,
  ICE_DRAGONS,
};

export function getTheme(theme: ContextTheme): ThemeColors {
  return THEME_MAP[theme] ?? MINIMALIST;
}

export const THEME_NAMES: Record<ContextTheme, string> = {
  MINIMALIST: 'Minimalist',
  DESIGN: 'Design',
  FORMAL: 'Formal',
  NATURE: 'Nature',
  DARK: 'Dark',
  DRAGONS: 'Dragons',
  ICE_DRAGONS: 'Ice Dragons',
};
